export const orbDefs = [
  {
    id: 'upload',
    label: 'Upload Notes',
    color: 0x00bfa5,
    icon: '↑',
    angle: Math.PI,
    radius: 5.2,
    speed: 0.28,
    yOff: 0.3,
    title: 'Upload Notes',
    desc: 'Drag & drop PDFs, slides, or text files. StudyAI extracts key concepts automatically.',
    chips: ['PDF', 'DOCX', 'TXT', 'PPTX'],
  },
  {
    id: 'chat',
    label: 'Ask AI',
    color: 0x7c5cfc,
    icon: '💬',
    angle: Math.PI * 0.55,
    radius: 5.8,
    speed: 0.22,
    yOff: 0.8,
    title: 'Ask AI',
    desc: 'Ask anything about your uploaded notes. Get instant, source-cited answers.',
    chips: ['GPT-4o', 'Context-aware', 'Instant'],
  },
  {
    id: 'quiz',
    label: 'Generate Quiz',
    color: 0xffab00,
    icon: '✓',
    angle: Math.PI * 0.05,
    radius: 5.8,
    speed: 0.19,
    yOff: 0.6,
    title: 'Quiz Mode',
    desc: 'Auto-generate MCQ, true/false, and short-answer quizzes from your material.',
    chips: ['MCQ', 'True/False', 'Auto-grade'],
  },
  {
    id: 'flashcards',
    label: 'Flashcards',
    color: 0xff6b6b,
    icon: '⟳',
    angle: 0,
    radius: 5.2,
    speed: 0.31,
    yOff: 0.4,
    title: 'Flashcards',
    desc: 'Spaced-repetition cards generated from your notes. Study smarter, not harder.',
    chips: ['Spaced Repetition', 'Auto-flip', 'Progress'],
  },
  {
    id: 'planner',
    label: 'Revision Planner',
    color: 0x2979ff,
    icon: '📅',
    angle: Math.PI * 1.5,
    radius: 4.5,
    speed: 0.15,
    yOff: -0.4,
    title: 'Planner',
    desc: 'AI-builds a personalised revision schedule based on your exam dates and weak topics.',
    chips: ['Weekly view', 'Reminders', 'Adaptive'],
  },
];
